name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
    - name: install modules
      run: npm install
    - name: rimraf dist
      run: npm run prebuild
    - name: nest build
      run: npm run build
    - name: prettier --write
      run: npm run format
    - name: nest start
      run: npm run start
    - name: node dist/main
      run: npm run start:prod
    - name: eslint
      run: npm run lint
    - name: jest
      run: npm run test
    - name: jest --watch
      run: npm run test:watch
    - name: jest --coverage
      run: npm run test:cov
    - name: node
      run: npm run test:debug
    - name: jest
      run: npm run test:e2e